language: node_js
os:
- linux
- osx
node_js:
- '6'
- '7'
- '8'
- '9'
- '10'
- '11'
- '12'
- '13'
- '14'
- '15'
- lts/*
- stable
sudo: false
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
- CC=gcc-4.8 CXX=g++-4.8
before_install:
- |
  if [[ ${TRAVIS_OS_NAME} == osx ]]; then
   export CXX=clang
   export CC=clang
  fi
- "$CC --version"
- "$CXX --version"
- env
install:
- npm install --build-from-source
before_deploy:
- node_modules/.bin/node-pre-gyp package
deploy:
  provider: releases
  tag_name: "$TRAVIS_TAG"
  draft: true
  api_key:
    secure: lgSczkbbnNx4pR83ebecwat4vpM+Il5vmxAePErkGxCzINycnf35ZJpUd/MLmk5gMD/nJTVRbhDRZ+oVwE6G1y4gWZrDvytFGnrMUULJEPi1SPTq+htIKgnlB0JSO+HGSgUXS1njIqaMnmPjgB0Ndvdw6m290mjy2IpEF0NrGKv3zDiSOUvgeeufuvfc1uJo34II3Q14nBdAhA/+xbKnHtJOf0Xy+WX0bw6YNNZ6jtGT6YShN2raQWJrSM1cqe/Y4ehrGMUtgR4wbfOlw2fqalXlvuUwI235lMuBc9bK1WHWMv9A2sCJsTJ8F6HmrYLlyIJZkEzKeOw67f+Cb47voFliif0gHhAkijqhZ/00/8nFuby/+wSEvIBF6ke8gLAum/qlSTPcK35bzj3LZHSRUJCK2zv5x7meIsr3JGIoIgYaEWHYqmgQjVYrLzP5T/7vKEeLuIRKAnYJmSRBZS/m1az5+9efNATC9ciGjOe0W6/Zdzu79iV4Z5l6t2PV6yxTbUho/COQnFn/60/Tt2rLCbJlCK4Gm3m/TEDQdUn3M3KnuyRSboKOLERHYiZEWc2wFJAiSVl4EUZyUXUqmIO9fXaFxZkmbr19/RDXiKysQ3NpU5RXTVCCIsGY8MzeZdHdzrCV0hCQUk9fwSczOp7bbeRFV+3kINqWHEb/4oPHMP8=
  file: build/stage/barhoumio/node-libtidy/releases/download/**/*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: barhoumio/node-libtidy
    tags: true
    condition: "${TRAVIS_TAG} == v*([0-9]).*([0-9]).*([0-9]) && ${TRAVIS_NODE_VERSION}
      == [0-9]*\n"
