language: node_js
os:
- linux
- osx
node_js:
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
- '10'
- lts/*
- stable
sudo: false
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
- CC=gcc-4.8 CXX=g++-4.8
before_install:
- |
  if [[ ${TRAVIS_OS_NAME} == osx ]]; then
   export CXX=clang
   export CC=clang
  fi
- "$CC --version"
- "$CXX --version"
- env
install:
- npm install --build-from-source
before_deploy:
- node_modules/.bin/node-pre-gyp package
deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  draft: true
  api_key:
    secure: FLeq5oP9gM+oyZQ9DiX4j/PWiMxpAy4c9yT8bOth+F4Ml3ACoB6Z/blINZsEUI9aZVgmlZna9E1KqEE/6S4SbwiX4DP7EHGojiqlBtc/ylRhluNFg1vTeWeyTNfrR3wiGbLgt/6UvIwDfUEoyzSzTll0tFLhKNhCuBrZPh6SQB4+kNxju85h4dWiRadspLiM/fFXRg+1RYpCj/oxJQW2L8nZtDDeFpxHOUlCnyLwlxOeT0Yk0kOByvgjitkly/jd9Xn3SAW+modTIkluEvLg+VR6hePI8iVXbdljOIBS4Yt009x1iTmjHb16d5sUdVeiK5phYhp3v0dICW7jK9ajxyBgyhz11aqZuUegLXOWYEiuWFQdeIuJM3tcRD5vBgjT1PUTkqQlUilQAzokK1b9rIwdoalp9aUxNRrS1qwZsR0VIS5wYdmlO0Us1S8yP8FHzH5a684bpHwSnRHkeaIS25YAb1qLf7GNChretqyoXKFpTv2BqOj+RgQjeb4tSxqxMjhIFSJnGhLpV6uDI12D3+yccA/RwG3eswl6vkwmeYxkD8XzWCEpTjvGRYIbZEZvNAs2hbVVAoAGt+5KYWKy8HSOyQt/am+895Ge4mJCg4IkJNY6Yndu/Gtffjt8NwlvxaEZfdr7KWe6uMn+cOsDgAInHx51l7BuIwunTO7hm4g=
  file: build/stage/barhoumio/node-libtidy/releases/download/**/*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
  repo: barhoumio/node-libtidy
  tags: true
  condition: >
   ${TRAVIS_TAG} == v*([0-9]).*([0-9]).*([0-9])
   && ${TRAVIS_NODE_VERSION} == [0-9]*
