environment:
  github_release_token:
    secure: Duzz7racpsOIDYAjEmNGNBVtOK092hHlepD/cYzZYaO2u6/KX/9hmeexQq0ARgRv
  matrix:
    - nodejs_version: 6
    - nodejs_version: 7
    - nodejs_version: 8
    - nodejs_version: 9
    - nodejs_version: 10
    - nodejs_version: 11
    - nodejs_version: 12
    - nodejs_version: 13
    - nodejs_version: 14
    - nodejs_version: 15

platform:
  - x86
  - x64

image: Visual Studio 2015

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g npm
  - node --version
  - npm --version
  - git submodule update --init --recursive

build_script:
  - npm install --build-from-source

test_script:
  - npm test

after_test:
  - node_modules/.bin/node-pre-gyp package

artifacts:
  - path: build\stage\barhoumio\node-libtidy\releases\download\**\*.tar.gz
    name: binary

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    artifact: binary
    auth_token: $(github_release_token)
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true
