environment:
  github_release_token:
    secure: Duzz7racpsOIDYAjEmNGNBVtOK092hHlepD/cYzZYaO2u6/KX/9hmeexQq0ARgRv
  matrix:
    - nodejs_version: 6
    - nodejs_version: 7
    - nodejs_version: 8
    - nodejs_version: 9
    - nodejs_version: 10
    - nodejs_version: 11
    - nodejs_version: 12
    - nodejs_version: 13
    - nodejs_version: 14
    - nodejs_version: 15
    - nodejs_version: 16
    - nodejs_version: 17
    - nodejs_version: 18
    - nodejs_version: 19
    - nodejs_version: 20
    - nodejs_version: 21
    - nodejs_version: 22
platform:
  - x86
  - x64

image:
  - Visual Studio 2022
  - Ubuntu2004
  - macos

install:
  - cmd: powershell Install-Product node $env:nodejs_version $env:platform
  - sh: |
        platform=$(uname -s)
        if [[ $platform == Linux ]]; then
        sudo apt-get remove nodejs
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update -y
        sudo apt-get install -y gcc-4.8 g++-4.8
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 \
                       --slave   /usr/bin/g++ g++ /usr/bin/g++-4.8
        sudo apt-get upgrade -y libstdc++6
        fi
  - sh: nvm install $nodejs_version
  - sh: nvm use $nodejs_version
  - node --version
  - npm --version
  - git submodule update --init --recursive

build_script:
  - npm install --build-from-source

test_script:
  - npm test

after_test:
  - node_modules/.bin/node-pre-gyp package

artifacts:
  - path: build\stage\barhoumio\node-libtidy\releases\download\**\*.tar.gz
    name: binary

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    artifact: binary
    auth_token: $(github_release_token)
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true
